version: 1.0
provider:
  name: faas
  gateway: http://192.168.99.100:31112
functions:
  helloworld:
    lang: go
    handler: ./helloworld
    image: kturcios/helloworld:latest
  spotify:
    lang: node10-express
    handler: ./spotify
    image: kturcios/spotify:latest
    environment:
      exec_timeout: 30s
    secrets:
      - ofc-functions
  node-microservice:
    lang: dockerfile
    handler: ./node-microservice
    image: kturcios/node-microservice:latest
