provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  helloworld:
    lang: go
    handler: ./helloworld
    image: kturcios/helloworld:latest
  test:
    lang: python
    handler: ./test
    image: kturcios/test:latest
