version: 1.0
provider:
  name: faas
  gateway: http://127.0.0.1:8080
functions:
  helloworld:
    lang: go
    handler: ./helloworld
    image: kturcios/helloworld:latest
  spotify:
    lang: node10-express
    handler: ./spotify
    image: kturcios/spotify:latest
    secrets:
      - client_id
